### ISSUE TITLE
Clean up altitudes to better conform to FIXM and increase extensibility

### ISSUE THREAD

**Issue by nasajoey** [nasa/utm-apis#49]
When we provide alt data, we currently wrap up altitude, units, and reference system into the field name (altitude_wgs84_ft).  FIXM and AIXM break these up to allow more flexibility.  To increase interoperability and reuse, break out altitude model and reference when necessary from other models.

The altitude model might be: 
altitude_value (double with some extreme bounds)
source (enum with only one value: ONBOARD_GPS)
vertical_reference (enum with only one value: W84)
units_of_measure (enum with only one value: FT)

Then a current field like Positions.altitude_gps_wgs84_ft would become Positions.altitude and it would point to an instance of the altitude model.

If design decisions are made in the future to accommodate more reference systems (e.g. AGL/SFC) or more units of measure (e.g. meters) or more sources, the model will be more readily extensible.

**Comment by nasajoey** [comment]
for reference: 

Vertical Distance ref:  https://www.fixm.aero/releases/FIXM-4.1.0/doc/schema_documentation_core/Measures_xsd.html#VerticalDistanceType

Units of measure: https://www.fixm.aero/releases/FIXM-4.1.0/doc/schema_documentation_core/UnitsOfMeasure_xsd.html#UomHeightType

**Comment by nasajoey** [comment]
This change is a little bigger than the other v4-draft changes I think.  I may start a separate branch and we can ease it in later.

**Comment by nasajoey** [comment]
merged alt branch into v4-draft-sprint1.  Might as well go through the pain of model updates now rather than later.

**Comment by nasajoey** [comment]
For reference:

```
  Altitude:
    type: object
    required:
      - altitude_value
      - vertical_reference
      - units_of_measure
    properties:
      altitude_value:
        description: >-
          The numeric value of the altitude. Note that min and max values are
          added as a sanity check. As use cases evolve and more options are
          made available in terms of units of measure or reference systems,
          these bounds should be re-evaluated.
        type: double
        minimum: -8000.0
        exclusiveMinimum: false
        maximum: 100000.0
        exclusiveMaximum: false
      vertical_reference:
        description: >-
          A code indicating the reference for a vertical distance. See AIXM 5.1
          and FIXM 4.1.0.

          Currently, UTM only allows WGS84 with no immediate plans to allow
          other options. FIXM and AIXM allow for 'SFC' which is equivalent to
          AGL.
        externalDocs:
          description: See FIXM 4.1.0 for further information.
          url: https://www.fixm.aero/releases/FIXM-4.1.0/doc/schema_documentation_core/Measures_xsd.html#VerticalReferenceType
        xml:
          name: VerticalReferenceType
          namespace: https://www.fixm.aero/nas/4.1
          prefix: fb
          attribute: false
        type: string
        enum:
          - W84
        minLength: 3
        maxLength: 3
      units_of_measure:
        description: >-
          The reference quantities used to express the value of altitude. See
          FIXM 4.1.

          Currently, UTM only allows feet with no immediate plans to allow
          other options.  FIXM allows for feet or meters.
        externalDocs:
          description: See FIXM 4.1.0 for further information.
          url: https://www.fixm.aero/releases/FIXM-4.1.0/doc/schema_documentation_core/UnitsOfMeasure_xsd.html#UomHeightType
        xml:
          name: UomHeightType
          namespace: https://www.fixm.aero/nas/4.1
          prefix: fb
          attribute: false
        type: string
        enum:
          - FT
        minLength: 2
        maxLength: 2
      source:
        description: >-
          Experimental field for testing and discussion to determine
          applicability.
        type: string
        enum:
          - ONBOARD_SENSOR
          - OTHER
        minLength: 5
        maxLength: 14
```
